### ISSUE TITLE
[EIP Bot] Support multiple files at once

### ISSUE THREAD

**Issue by alita-moore** [alita-moore/PM#4]
![image](https://user-images.githubusercontent.com/26529820/122361805-367b8d00-cf1d-11eb-882c-91a42577eed3.png)
https://github.com/ethereum/EIPs/pull/3612/files

**Comment by lilchris502** [comment]
> ![image](https://user-images.githubusercontent.com/26529820/122361805-367b8d00-cf1d-11eb-882c-91a42577eed3.png)
> https://github.com/ethereum/EIPs/pull/3612/files

xpub6CA73cCqXUHCVV2EUoV3aaCiVDBeg28VCPDjnLaWEnCps1Q4CFBaxBXNDBpYwwxWrvE88Bhp53hreqhmqXJr8KDzAEPBrVUTtCqkEW6X8e9

**Comment by alita-moore** [comment]
this is implemented by https://github.com/ethereum/EIP-Bot/compare/b6cf981087e888b5d7fbd4726458c453f8491532...310fd6cead3459789b27043539886d929fd2930e
